In [5]:
!pip install numpy


In [17]:
# 1
import numpy as np

a1=np.arange(0,16)
display(a1)
display(np.reshape(a1,(4,4)))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
# 2
a2=np.arange(10,50,5)
display(a2)
display(np.reshape(a2,(2,4)))

array([10, 15, 20, 25, 30, 35, 40, 45])

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [29]:
# 3
a3 = np.random.randint(1, 100, (3, 3))
display(a3)
display("max", a3.max())
display("min", a3.min())

array([[75, 73, 95],
       [50, 20, 92],
       [46, 66, 62]], dtype=int32)

'max'

np.int32(95)

'min'

np.int32(20)

In [37]:
a4=np.linspace(0, 20, 10, dtype=int)
display(a4)
display(a4[:5])
display(a4[::2])
display(a4[::-1])

array([ 0,  2,  4,  6,  8, 11, 13, 15, 17, 20])

array([0, 2, 4, 6, 8])

array([ 0,  4,  8, 13, 17])

array([20, 17, 15, 13, 11,  8,  6,  4,  2,  0])

In [45]:
# 5
a5 = np.random.randint(1, 50, (4, 5))
display(a5)
display(a5[1][3])

array([[21, 24, 21, 13,  9],
       [ 4,  3, 22, 21, 18],
       [19,  3,  7, 32, 19],
       [21, 20, 28, 25, 45]], dtype=int32)

np.int32(21)

In [57]:
# 6
a6=np.linspace(0, 100, 15, dtype=int)
display(a6)
display(a6.argmax())
display(a6.argmin())

copy_a6 = a6.copy()
copy_a6_1=copy_a6 % 5
display(copy_a6_1)
display((copy_a6[(copy_a6 < 50) | (copy_a6>10)]))

array([  0,   7,  14,  21,  28,  35,  42,  50,  57,  64,  71,  78,  85,
        92, 100])

np.int64(14)

np.int64(0)

array([0, 2, 4, 1, 3, 0, 2, 0, 2, 4, 1, 3, 0, 2, 0])

array([  0,   7,  14,  21,  28,  35,  42,  50,  57,  64,  71,  78,  85,
        92, 100])